version: '3'

services:
  app:
    build: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./src:/usr/app/src:ro
      - ./package.json:/usr/app/package.json
      - ./package-lock.json:/usr/app/package-lock.json
    env_file:
      - .env
    depends_on:
      - sql
  sql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: discordBot
      MYSQL_USER: bot
      MYSQL_PASSWORD: password
    expose:
      - 3306
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./db-data:/var/lib/mysql
