#!/bin/bash

set -e

prod=false;
if [ "${NODE_ENV}" == "production" ]; then
	prod=true;
	echo "Running in Production Mode"
else
	echo "Running in Development Mode"
fi

if [ ! -d "/usr/app/node_modules" ]; then
	echo "Installing Node Modules..."
	
	if [ $prod == true ]; then
		npm install --quiet --production /usr/app
	else
		npm install --quiet /usr/app
	fi

fi

if [ -z "$@" ]; then
	echo "Waiting for database..."

	if [ $prod == true ]; then
		/wait-for sql:3306 -- npm run --prefix /usr/app start
	else
		/wait-for sql:3306 -- npm run --prefix /usr/app dev
	fi
else
	exec "$@"
fi
